Вторая четверть урок 1
jonmd87/JavaGB pull request #10
Opened 2021-12-31 15:03 UTC by jonmd87

2022-01-02 16:47 UTC, efserg requested changes

2022-01-02 16:47 UTC, efserg commented on 2Quarter/src/main/java/ru/gb/gerasimenko/Obstruction.java
> +        }
Бессмысленный  код. Зачем это понадобилось?

2022-01-02 16:47 UTC, efserg commented on 2Quarter/src/main/java/ru/gb/gerasimenko/Obstruction.java
> +            player.
А этот код вообще не рабочий

2022-01-02 16:47 UTC, efserg commented on 2Quarter/src/main/java/ru/gb/gerasimenko/Obstruction.java
> +    private static Object[] createObstructions() {
Зачем вы везде используете Object? Просто создайте общий интерфейс (или абстрактный класс) для препятствий

2022-01-02 16:47 UTC, efserg commented on 2Quarter/src/main/java/ru/gb/gerasimenko/Obstruction.java
> +    private static Object[] createPlayers() {
Опять Object :(

2022-01-02 16:47 UTC, efserg commented on 2Quarter/src/main/java/ru/gb/gerasimenko/Obstruction.java
> +                if(arr[i] instanceof Wall) {
Слишком много instanceOf

2022-01-07 12:52 UTC, jonmd87 commented on 2Quarter/Lesson1/src/main/java/ru/gb/gerasimenko/App.java
> +        if (o instanceof Wall) {
Все же не смог обойтись без instanceOf

2022-01-07 12:52 UTC, jonmd87 commented on 2Quarter/Lesson1/src/main/java/ru/gb/gerasimenko/App.java
> +        else if (o instanceof Treadmill) {
Все же не смог обойтись без instanceOf

2022-01-07 16:45 UTC, merged